# MODバージョンを設定する
version=0.1.1-alpha
# グループIDを設定する
group=com.sayuki
# Javaバージョンを指定する
java_version=17

# Minecraftバージョンを指定する
minecraft_version=1.20.1
# MOD名を設定する
mod_name=MakeBackup
# MOD作者を設定する
mod_author=Shiraishi Sayuki
# MOD IDを設定する
mod_id=makebackup
# ライセンスを設定する
license=ARR
# クレジット表記を設定する
credits=
# MOD説明を設定する
description=FTP/SFTP/Google Driveに対応した、Minecraftサーバー向けのシンプルなバックアップMOD
# 対応Minecraftバージョン範囲を設定する
minecraft_version_range=[1.20.1, 1.21)
# ParchmentマッピングのMinecraftバージョンを指定する
parchment_minecraft=1.20.1
# Parchmentバージョンを指定する
parchment_version=2023.09.03

# Adventureライブラリバージョンを指定する
adventure_version=4.14.0

# Fabric APIバージョンを指定する
fabric_version=0.92.1+1.20.1
# Fabric Loaderバージョンを指定する
fabric_loader_version=0.16.9

# Forgeバージョンを指定する
forge_version=47.2.30
# Forge Loaderバージョン範囲を指定する
forge_loader_version_range=[47,)

# Gradle JVM引数を設定する
org.gradle.jvmargs=-Xmx3G
# Gradleデーモンを無効化する
org.gradle.daemon=false
